#' @title Test prediction model for immunotherapy response
#' @description Test a naive bayes model.
#' @param xlearn model generated by build_Model() function
#' @param ylearn an SummarizedExperiment(SE) object or a list consists of SE objects. The colData of SE objects must contain response information.
#' @param nIter an SummarizedExperiment(SE) object or a list consists of SE objects. The colData of SE objects must contain response information.

LogitBoost <- function(xlearn, ylearn, nIter=ncol(xlearn)){
  lablist <- sort(unique(ylearn))
  nClass  <- length(lablist)

  if (nClass>2) {
    Stump <- NULL
    for (jClass in 1:nClass) {
      y <- as.numeric(ylearn!=lablist[jClass])
      Stump <- cbind(Stump, LogitBoost(xlearn, y, nIter)$Stump)
    }
    object <- list(Stump=Stump, lablist=lablist)
    class(object) <- "LogitBoost"
    return(object)
  }

  Mask <- is.na(xlearn)
  if (any(Mask)) xlearn[Mask] <- Inf
  ylearn = as.numeric(ylearn!=lablist[1])
  nLearn = nrow(xlearn)
  nFeat  = ncol(xlearn)

  f      = 0
  p      = numeric(nLearn)+1/2
  Stump  = matrix(0, nIter,3)
  colnames(Stump) = c("feature", "threshhold", "sign")
  Thresh =            matrix(0, nLearn, nFeat)
  Index  = matrix(as.integer(0), nLearn, nFeat)
  Mask   = matrix(as.logical(0), nLearn, nFeat)
  repts  = as.logical(numeric(nFeat))

  for (iFeat in 1:nFeat) {
    x = sort(xlearn[,iFeat], index=TRUE)
    Thresh[,iFeat] = x[[1]]
    Index [,iFeat] = x[[2]]
    Mask  [,iFeat] = c((diff(Thresh[,iFeat])!=0), TRUE)
    repts [ iFeat] = !all(Mask[,iFeat])
  }

  jFeat = 0
  for (m in 1:nIter) {
    w = pmax(p*(1-p), 1e-24)
    z = (ylearn-p)/w
    w = w/sum(w)
    ls1 = sum(w*(z+1)^2)
    ls2 = sum(w*(z-1)^2)
    MinLS = max(ls1,ls2)
    wz  = 4 * w * z
    for (iFeat in 1:nFeat) {
      if (iFeat==jFeat) next
      Col = Thresh[,iFeat]
      LS  = cumsum(wz[Index[,iFeat]])
      if (repts[iFeat]) {
        mask = Mask[,iFeat]
        Col = Col[mask]
        LS  = LS [mask]
      }
      iLS1 = which.max(LS)
      iLS2 = which.min(LS)
      vLS1 = ls1-LS[iLS1]
      vLS2 = ls2+LS[iLS2]
      if (MinLS>vLS1) { stump=c(iFeat, Col[iLS1],  1); MinLS=vLS1; }
      if (MinLS>vLS2) { stump=c(iFeat, Col[iLS2], -1); MinLS=vLS2; }
    }

    Stump[m,] = stump
    jFeat = stump[1]
    f = f + stump[3] * (2*( xlearn[,jFeat]<=stump[2] )-1)
    p = 1/(1+exp(-f))

    y = (f>0)
    y[f==0] = 0.5
    Conv = sum(abs(ylearn-y))
  }
  object = list(Stump=Stump, lablist=lablist)
  class(object) <- "LogitBoost"
  object$features <- colnames(xlearn)
  return(object)
}
