#' @title Test prediction model for immunotherapy response
#' @description Generate a naive bayes model.
#' @param Model model generated by build_Model() function
#' @param SE an SummarizedExperiment(SE) object or a list consists of SE objects. The colData of SE objects must contain response information.
#' @export

test_Model <- function(Model, SE){
  browser()
  md_type <- attributes(Model)$class[1]
  switch(md_type,
         naiveBayes = test_NB_model(Model, SE),
         randomForest = test_RF_model(Model, SE),
         svm = test_SVM_model(Model, SE),
         predictor = test_CC_model(Model, SE),
         boosting =test_Adaboost_model(Model, SE),
         LogitBoost = test_Logitboost_model(Model, SE),
         glm = test_Logistics_model(Model, SE))
}

#' @title Test prediction model for immunotherapy response
#' @description Test a naive bayes model.
#' @param Model model generated by build_Model() function
#' @param SE an SummarizedExperiment(SE) object or a list consists of SE objects. The colData of SE objects must contain response information.
#' @importFrom e1071 naiveBayes
#' @importFrom pROC roc

test_NB_model <- function(Model, SE){
  N_R <- all(Model$levels %in% c('NR','R'))
  selected_gene <- rownames(Model$importance)
  data <- dataProcess(SE,selected_gene, FALSE, N_R, TRUE)
  value <- as.numeric(predict(Model, t(data[[1]]), type = 'raw')[,1])
  ROC <- roc(data[[2]]$response, value)
}

#' @title Test prediction model for immunotherapy response
#' @description Test a naive bayes model.
#' @param Model model generated by build_Model() function
#' @param SE an SummarizedExperiment(SE) object or a list consists of SE objects. The colData of SE objects must contain response information.
#' @importFrom pROC roc

test_RF_model <- function(Model, SE){
  N_R <- all(Model$levels %in% c('NR','R'))
  selected_gene <- rownames(Model$importance)
  data <- dataProcess(SE,selected_gene, FALSE, N_R, FALSE)
  value <- as.numeric(predict(Model, t(data[[1]]), type = 'vote')[,1])
  ROC <- roc(data[[2]]$response, value)
}

#' @title Test prediction model for immunotherapy response
#' @description Test a naive bayes model.
#' @param Model model generated by build_Model() function
#' @param SE an SummarizedExperiment(SE) object or a list consists of SE objects. The colData of SE objects must contain response information.
#' @importFrom pROC roc

test_SVM_model <- function(Model, SE){
  selected_gene <- names(Model$x.scale$`scaled:center`)
  data <- dataProcess(SE,selected_gene, FALSE, TRUE, FALSE)
  value <- predict(Model, t(data[[1]]),type='eps-regression')
  ROC <- roc(data[[2]]$response, value)
}

#' @title Test prediction model for immunotherapy response
#' @description Test a naive bayes model.
#' @param Model model generated by build_Model() function
#' @param SE an SummarizedExperiment(SE) object or a list consists of SE objects. The colData of SE objects must contain response information.
#' @importFrom pROC roc
#' @importFrom cancerclass predict

test_CC_model <- function(Model, SE){
  selected_gene <- rownames(Model@predictor)
  data <- dataProcess(SE,selected_gene, FALSE, TRUE, FALSE)
  exprs <- data[[1]]
  pData <- data[[2]]
  rownames(pData) <- pData$sample_id
  pData$class <- c(extract_label('MEL_GSE78220'), extract_label('MEL_PRJEB23709'))
  identical(rownames(pData),colnames(exprs))
  metadata <- data.frame(labelDescription = colnames(pData), row.names = colnames(pData))
  adf <- new("AnnotatedDataFrame", data = as.data.frame(pData), varMetadata = metadata)

  exampleSet2 <- new("ExpressionSet", exprs = exprs, phenoData = adf)
  prediction <- cancerclass::predict(Model, exampleSet2, positive = "R", dist = "cor")
  value <- as.numeric(prediction@prediction[,3])
  ROC <- roc(data[[2]]$response, value)
}

#' @title Test prediction model for immunotherapy response
#' @description Test a naive bayes model.
#' @param Model model generated by build_Model() function
#' @param SE an SummarizedExperiment(SE) object or a list consists of SE objects. The colData of SE objects must contain response information.
#' @importFrom pROC roc
#' @importFrom adabag predict.boosting

test_Adaboost_model <- function(Model, SE){
  selected_gene <- names(Model$importance)
  data <- dataProcess(SE,selected_gene, FALSE, TRUE, FALSE)
  pred <- predict.boosting(Model, as.data.frame(t(data[[1]])))
  value <- pred$votes[,1]
  ROC <- roc(data[[2]]$response, value)
}

#' @title Test prediction model for immunotherapy response
#' @description Test a naive bayes model.
#' @param Model model generated by build_Model() function
#' @param SE an SummarizedExperiment(SE) object or a list consists of SE objects. The colData of SE objects must contain response information.
#' @importFrom pROC roc

test_Logitboost_model <- function(Model, SE){
  selected_gene <- Model$features
  data <- dataProcess(SE,selected_gene, FALSE, TRUE, FALSE)
  value <- predict(Model,t(data[[1]]),type = 'raw')[,1]
  ROC <- roc(data[[2]], value)
}

#' @title Test prediction model for immunotherapy response
#' @description Test a naive bayes model.
#' @param Model model generated by build_Model() function
#' @param SE an SummarizedExperiment(SE) object or a list consists of SE objects. The colData of SE objects must contain response information.
#' @importFrom pROC roc

test_Logistics_model <- function(Model, SE){
  selected_gene <- names(Model$coefficients[-1])
  data <- dataProcess(SE,selected_gene, FALSE, TRUE, FALSE)
  df <- data.frame(t(max_min_normalization(data[[1]])))
  value <- as.numeric(predict(Model, df, type = 'response'))
  ROC <- roc(data[[2]]$response, value)
}
