#' @title Test prediction model for immunotherapy response
#' @description Generate a naive bayes model.
#' @param Model the model that you want to test, which is generated by the build_Model() function.
#' @param SE the dataset you wish to use to test your model. A SummarizedExperiment (SE) object, which can be either a single SE object or a list of SE objects. Note that for each SE object, the colData must contain treatment information under the column name Treatment.
#' @param mtr the meta information.
#' @param meta meta data of samples
#' @param PT_drop If TRUE, only Untreated patient will be use for model training.
#' @export

test_Model <- function(Model,SE=NULL, mtr=NULL, meta=NULL, PT_drop=TRUE){
  if(!missing(SE))
    test_Model.default(Model, SE, PT_drop)
  else
    test_Model.matrix(Model, mtr, meta)
}


#' @title Test prediction model for immunotherapy response
#' @description Generate a naive bayes model.
#' @param Model the model that you want to test, which is generated by the build_Model() function.
#' @param SE the dataset you wish to use to test your model. A SummarizedExperiment (SE) object, which can be either a single SE object or a list of SE objects. Note that for each SE object, the colData must contain treatment information under the column name Treatment.
#' @param PT_drop If TRUE, only Untreated patient will be use for model training.
#' @export

test_Model.default <- function(Model, SE, PT_drop=TRUE){
  md_type <- attributes(Model)$class[1]

  switch(md_type,
         naiveBayes = test_NB_model(Model, SE, PT_drop=PT_drop),
         randomForest = test_RF_model(Model, SE, PT_drop=PT_drop),
         svm = test_SVM_model(Model, SE, PT_drop=PT_drop),
         predictor = test_CC_model(Model, SE, PT_drop=PT_drop),
         boosting = test_Adaboost_model(Model, SE, PT_drop=PT_drop),
         LogitBoost = test_Logitboost_model(Model, SE, PT_drop=PT_drop),
         glm = test_Logistics_model(Model, SE, PT_drop=PT_drop),
         penfit = test_SURV_Model(Model, SE, PT_drop))
}

#' @title Test prediction model for immunotherapy response
#' @description Generate a naive bayes model.
#' @param Model the model that you want to test, which is generated by the build_Model() function.
#' @param mtr the result matrix of TME deconvolution.
#' @param meta meta data of samples
#' @export

test_Model.matrix <- function(mtr, meta, Model){
  SE_obj <- SummarizedExperiment::SummarizedExperiment(assays=S4Vectors::SimpleList(mtr),
                                                       colData=S4Vectors::DataFrame(meta),
                                                       checkDimnames=TRUE)
  test_Model.default(SE_obj, Model)
}


#' @title Test prediction model for immunotherapy response
#' @description Test a naive bayes model.
#' @param Model model generated by build_Model() function
#' @param SE an SummarizedExperiment(SE) object or a list consists of SE objects. The colData of SE objects must contain response information.
#' @param PT_drop If TRUE, only Untreated patient will be use for model training.

test_NB_model <- function(Model, SE, PT_drop){
  N_R <- all(Model$levels %in% c('N','R'))
  selected_gene <- names(Model$table)
  data <- dataProcess(SE,selected_gene, FALSE, N_R, FALSE)
  if(PT_drop)
    data <- PT_filter(data)
  data[[1]] <-
  apply(data[[1]], 2, function(x){
    ifelse(x>=Model$threshold[rownames(data[[1]])],"HIGH","LOW")
  })
  value <- stats::predict(Model, t(data[[1]]), type = 'raw')
  ROC <- pROC::roc(data[[2]]$response_NR, value[,1]/value[,2])
  result <- generate_result(ROC)
  result[[3]] <- ifelse(value[,1]>=value[,2],'N','R')
  result
}

#' @title Test prediction model for immunotherapy response
#' @description Test a naive bayes model.
#' @param Model model generated by build_Model() function
#' @param SE an SummarizedExperiment(SE) object or a list consists of SE objects. The colData of SE objects must contain response information.
#' @param PT_drop If TRUE, only Untreated patient will be use for model training.
#' @importFrom pROC roc

test_RF_model <- function(Model, SE, PT_drop){
  N_R <- all(Model$levels %in% c('NR','R'))
  selected_gene <- rownames(Model$importance)
  data <- dataProcess(SE,selected_gene, FALSE, N_R, FALSE)
  if(PT_drop)
    data <- PT_filter(data)
  pred <- stats::predict(Model, t(data[[1]]), type = 'vote')

  predictor <- pred[,1]/pred[,2]
  predictor[predictor == Inf] <- sort(unique(predictor),decreasing = TRUE)[2]
  predictor[predictor == -Inf] <- sort(unique(predictor))[2]
  ROC <- roc(data[[2]]$response, predictor)

  result <- generate_result(ROC)
  result[[3]] <- ifelse(pred[,1]>=pred[,2],'N','R')
  result
}

#' @title Test prediction model for immunotherapy response
#' @description Test a naive bayes model.
#' @param Model model generated by build_Model() function
#' @param SE an SummarizedExperiment(SE) object or a list consists of SE objects. The colData of SE objects must contain response information.
#' @param PT_drop If TRUE, only Untreated patient will be use for model training.

test_SVM_model <- function(Model, SE, PT_drop){
  selected_gene <- Model$features
  data <- dataProcess(SE,selected_gene, FALSE, TRUE, FALSE)
  if(PT_drop)
    data <- PT_filter(data)
  value <- stats::predict(Model, t(data[[1]]),type='eps-regression')
  ROC <- pROC::roc(data[[2]]$response, value)
  generate_result(ROC)
}

#' @title Test prediction model for immunotherapy response
#' @description Test a naive bayes model.
#' @param Model model generated by build_Model() function
#' @param SE an SummarizedExperiment(SE) object or a list consists of SE objects. The colData of SE objects must contain response information.
#' @param PT_drop If TRUE, only Untreated patient will be use for model training.

test_CC_model <- function(Model, SE, PT_drop){
  selected_gene <- rownames(Model@predictor)
  data <- dataProcess(SE,selected_gene, FALSE, TRUE, FALSE)
  if(PT_drop)
    data <- PT_filter(data)
  pData <- data.frame(class = data[[2]]$response, row.names = colnames(data[[1]]))
  metadata <- data.frame(labelDescription = colnames(pData), row.names = colnames(pData))
  adf <- new("AnnotatedDataFrame", data = pData, varMetadata = metadata)
  exampleSet <- methods::new("ExpressionSet", exprs = data[[1]], phenoData = adf)

  prediction <- cancerclass::predict(Model, exampleSet, positive = "R",
                                     dist = "cor")
  value <- as.numeric(prediction@prediction[,5])
  ROC <- pROC::roc(data[[2]]$response, value)
  result <- generate_result(ROC)
  result[[3]] <- prediction@prediction[,2]
  result
}

#' @title Test prediction model for immunotherapy response
#' @description Test a naive bayes model.
#' @param Model model generated by build_Model() function
#' @param SE an SummarizedExperiment(SE) object or a list consists of SE objects. The colData of SE objects must contain response information.
#' @param PT_drop If TRUE, only Untreated patient will be use for model training.
#' @importFrom pROC roc

test_Adaboost_model <- function(Model, SE, PT_drop){
  selected_gene <- Model$features
  data <- dataProcess(SE,selected_gene, FALSE, TRUE, FALSE)
  if(PT_drop)
    data <- PT_filter(data)
  rownames(data[[1]]) <- sub("-",".",rownames(data[[1]]))
  pred <- adabag::predict.boosting(Model, as.data.frame(t(data[[1]])))
  value <- pred$votes[,1]
  ROC <- roc(data[[2]]$response, value)
  result <- generate_result(ROC)
  result[[3]] <- pred$class
  result
}

#' @title Test prediction model for immunotherapy response
#' @description Test a naive bayes model.
#' @param Model model generated by build_Model() function
#' @param SE an SummarizedExperiment(SE) object or a list consists of SE objects. The colData of SE objects must contain response information.
#' @param PT_drop If TRUE, only Untreated patient will be use for model training.
#' @importFrom pROC roc

test_Logitboost_model <- function(Model, SE, PT_drop){
  selected_gene <- Model$features
  data <- dataProcess(SE,selected_gene, FALSE, TRUE, FALSE)
  if(PT_drop)
    data <- PT_filter(data)
  value <- caTools::predict.LogitBoost(Model,t(data[[1]]),type = 'raw')
  ROC <- roc(data[[2]]$response, value[,1]/value[,2])
  result <- generate_result(ROC)
  result[[3]] <- ifelse(value[,1]>=value[,2],'N','R')
  return(result)
}


#' @title Test prediction model for immunotherapy response
#' @description Test a naive bayes model.
#' @param Model model generated by build_Model() function
#' @param SE an SummarizedExperiment(SE) object or a list consists of SE objects. The colData of SE objects must contain response information.
#' @param PT_drop If TRUE, only Untreated patient will be use for model training.
#' @importFrom pROC roc

test_Logistics_model <- function(Model, SE, PT_drop){
  selected_gene <- names(Model$coefficients[-1])
  data <- dataProcess(SE,selected_gene, FALSE, TRUE, FALSE)
  if(PT_drop)
    data <- PT_filter(data)
  df <- data.frame(t(max_min_normalization(data[[1]])))
  value <- as.numeric(stats::predict(Model, df, type = 'response'))
  ROC <- roc(data[[2]]$response_NR, value)
  generate_result(ROC)
}


#' @title Test Lasso cox prediction model for immunotherapy response
#' @description Test a Lasso cox model.
#' @param Model model generated by build_Model() function
#' @param SE an SummarizedExperiment(SE) object or a list consists of SE objects. The colData of SE objects must contain response information.
#' @param PT_drop If TRUE, only Untreated patient will be use for model training.

test_SURV_Model <- function(Model, SE, PT_drop){
  selected_feature <- Model@penalized
  data <- dataProcess(SE,names(selected_feature), FALSE, TRUE, FALSE)
  if(PT_drop)
    data <- PT_filter(data)

  prediction <- t(data[[1]]) %*% selected_feature
  status <- sub('Dead','1', data[[2]]$vital.status) %>%
    sub('Alive','0',.) %>%
    as.numeric()

  df <- na.omit(data.frame(time=data[[2]]$overall.survival..days., status))
  if(nrow(df) == 0)
    stop("There is no survival information available for the patients. Please review your dataset.")

  RC <- Hmisc::rcorr.cens(prediction,
                          survival::Surv(data[[2]]$overall.survival..days., status))
  se <- RC['S.D']/2
  C <- RC['C Index']
  result <- c(C, C-1.96*se, C+1.96*se)
  names(result) <- c('c-index', '95% LCI', '95% UCI')
  result
}


#' @title Test prediction model for immunotherapy response
#' @description Test a naive bayes model.
#' @param ROC the roc object

generate_result <- function(ROC){
  figure <- pROC::ggroc(ROC, color = 'black', size = 1 ) +
    ggplot2::geom_segment(ggplot2::aes(x = 0, xend = 1, y = 1, yend = 0),
                          color="darkgrey",size=0.5,linetype="solid") +
    ggplot2::annotate("text", x = 0.30, y = 0.42,
                      label = paste0("AUC=",round(ROC$auc,digits=4)), size = 4.5) +
    ggplot2::coord_fixed() +
    ggplot2::theme_bw() +
    ggplot2::theme(panel.grid = element_blank())
  return(list(ROC,figure))
}
