#' @title Test prediction model for immunotherapy response
#' @description Generate a naive bayes model.
#' @param Model the model that you want to test, which is generated by the build_Model() function.
#' @param SE the dataset you wish to use to test your model. A SummarizedExperiment (SE) object, which can be either a single SE object or a list of SE objects. Note that for each SE object, the colData must contain treatment information under the column name Treatment.
#' @param mtr the meta information.
#' @param meta meta data of samples
#' @export

test_Model <- function(Model,SE=NULL, mtr=NULL, meta=NULL){
  if(!missing(SE))
    test_Model.default(Model, SE)
  else
    test_Model.matrix(Model, mtr, meta)
}


#' @title Test prediction model for immunotherapy response
#' @description Generate a naive bayes model.
#' @param Model the model that you want to test, which is generated by the build_Model() function.
#' @param SE the dataset you wish to use to test your model. A SummarizedExperiment (SE) object, which can be either a single SE object or a list of SE objects. Note that for each SE object, the colData must contain treatment information under the column name Treatment.
#' @export

test_Model.default <- function(Model, SE){
  md_type <- attributes(Model)$class[1]

  return(switch(md_type,
                naiveBayes = test_NB_model(Model, SE),
                randomForest = test_RF_model(Model, SE),
                svm = test_SVM_model(Model, SE),
                predictor = test_CC_model(Model, SE),
                boosting =test_Adaboost_model(Model, SE),
                LogitBoost = test_Logitboost_model(Model, SE),
                glm = test_Logistics_model(Model, SE)))
}

#' @title Test prediction model for immunotherapy response
#' @description Generate a naive bayes model.
#' @param Model the model that you want to test, which is generated by the build_Model() function.
#' @param mtr the result matrix of TME deconvolution.
#' @param meta meta data of samples
#' @export

test_Model.matrix <- function(mtr, meta, Model){
  SE_obj <- SummarizedExperiment::SummarizedExperiment(assays=S4Vectors::SimpleList(mtr),
                                                       colData=S4Vectors::DataFrame(meta),
                                                       checkDimnames=TRUE)
  test_Model.default(SE_obj, Model)
}


#' @title Test prediction model for immunotherapy response
#' @description Test a naive bayes model.
#' @param Model model generated by build_Model() function
#' @param SE an SummarizedExperiment(SE) object or a list consists of SE objects. The colData of SE objects must contain response information.

test_NB_model <- function(Model, SE){
  N_R <- all(Model$levels %in% c('N','R'))
  selected_gene <- names(Model$table)
  data <- dataProcess(SE,selected_gene, FALSE, N_R, FALSE)
  data[[1]] <-
  apply(data[[1]], 2, function(x){
    ifelse(x>=Model$threshold[rownames(data[[1]])],"HIGH","LOW")
  })
  value <- as.numeric(predict(Model, t(data[[1]]), type = 'raw')[,1])
  ROC <- pROC::roc(data[[2]]$response_NR, value)
  generate_result(ROC)
}

#' @title Test prediction model for immunotherapy response
#' @description Test a naive bayes model.
#' @param Model model generated by build_Model() function
#' @param SE an SummarizedExperiment(SE) object or a list consists of SE objects. The colData of SE objects must contain response information.
#' @importFrom pROC roc

test_RF_model <- function(Model, SE){
  N_R <- all(Model$levels %in% c('NR','R'))
  selected_gene <- rownames(Model$importance)
  data <- dataProcess(SE,selected_gene, FALSE, N_R, FALSE)
  value <- as.numeric(predict(Model, t(data[[1]]), type = 'vote')[,1])
  ROC <- roc(data[[2]]$response, value)
  generate_result(ROC)
}

#' @title Test prediction model for immunotherapy response
#' @description Test a naive bayes model.
#' @param Model model generated by build_Model() function
#' @param SE an SummarizedExperiment(SE) object or a list consists of SE objects. The colData of SE objects must contain response information.

test_SVM_model <- function(Model, SE){
  selected_gene <- Model$features
  data <- dataProcess(SE,selected_gene, FALSE, TRUE, FALSE)
  value <- predict(Model, t(data[[1]]),type='eps-regression')
  ROC <- pROC::roc(data[[2]]$response, value)
  generate_result(ROC)
}

#' @title Test prediction model for immunotherapy response
#' @description Test a naive bayes model.
#' @param Model model generated by build_Model() function
#' @param SE an SummarizedExperiment(SE) object or a list consists of SE objects. The colData of SE objects must contain response information.

test_CC_model <- function(Model, SE){
  browser()
  selected_gene <- rownames(Model@predictor)
  data <- dataProcess(SE,selected_gene, FALSE, TRUE, FALSE)
  pData <- data.frame(class = data[[2]]$response, row.names = colnames(data[[1]]))
  metadata <- data.frame(labelDescription = colnames(pData), row.names = colnames(pData))
  adf <- new("AnnotatedDataFrame", data = pData, varMetadata = metadata)
  exampleSet <- methods::new("ExpressionSet", exprs = data[[1]], phenoData = adf)

  prediction <- cancerclass::predict(Model, exampleSet, positive = "R",
                                     dist = "cor")
  value <- as.numeric(prediction@prediction[, 3])
  ROC <- pROC::roc(data[[2]]$response, value)
  generate_result(ROC)
}

#' @title Test prediction model for immunotherapy response
#' @description Test a naive bayes model.
#' @param Model model generated by build_Model() function
#' @param SE an SummarizedExperiment(SE) object or a list consists of SE objects. The colData of SE objects must contain response information.
#' @importFrom pROC roc

test_Adaboost_model <- function(Model, SE){
  selected_gene <- Model$features
  data <- dataProcess(SE,selected_gene, FALSE, TRUE, FALSE)
  rownames(data[[1]]) <- sub("-",".",rownames(data[[1]]))
  pred <- adabag::predict.boosting(Model, as.data.frame(t(data[[1]])))
  value <- pred$votes[,1]
  ROC <- roc(data[[2]]$response, value)
  generate_result(ROC)
}

#' @title Test prediction model for immunotherapy response
#' @description Test a naive bayes model.
#' @param Model model generated by build_Model() function
#' @param SE an SummarizedExperiment(SE) object or a list consists of SE objects. The colData of SE objects must contain response information.
#' @importFrom pROC roc

test_Logitboost_model <- function(Model, SE){
  selected_gene <- Model$features
  data <- dataProcess(SE,selected_gene, FALSE, TRUE, FALSE)
  value <- caTools::predict.LogitBoost(Model,t(data[[1]]),type = 'raw')[,1]
  ROC <- roc(data[[2]]$response, value)
  generate_result(ROC)
}

#' @title Test prediction model for immunotherapy response
#' @description Test a naive bayes model.
#' @param Model model generated by build_Model() function
#' @param SE an SummarizedExperiment(SE) object or a list consists of SE objects. The colData of SE objects must contain response information.
#' @importFrom pROC roc

test_Logistics_model <- function(Model, SE){
  selected_gene <- names(Model$coefficients[-1])
  data <- dataProcess(SE,selected_gene, FALSE, TRUE, FALSE)
  df <- data.frame(t(max_min_normalization(data[[1]])))
  value <- as.numeric(stats::predict(Model, df, type = 'response'))
  ROC <- roc(data[[2]]$response_NR, value)
  generate_result(ROC)
}


#' @title Test prediction model for immunotherapy response
#' @description Test a naive bayes model.
#' @param ROC the roc object

generate_result <- function(ROC){
  figure <- pROC::ggroc(ROC, color = 'black', size = 1 ) +
    ggplot2::geom_segment(ggplot2::aes(x = 0, xend = 1, y = 1, yend = 0),
                          color="darkgrey",size=0.5,linetype="solid") +
    ggplot2::annotate("text", x = 0.30, y = 0.42,
                      label = paste0("AUC=",round(ROC$auc,digits=4)), size = 4.5) +
    ggplot2::coord_fixed() +
    ggplot2::theme_bw() +
    ggplot2::theme(panel.grid = element_blank())
  return(list(ROC,figure))
}
